import { shelterOutcome } from "./story/shelter";
import { freightOutcome } from "./story/freight";
import { shiftResponse } from "./story/employment";
import { equippedKits } from "./loadout";
import type { GameState } from "./types";

export const FRAGMENTS = [
  { id: "signature", flag: "memory_signature", time: "02:13", title: "The signature", source: "Mara's recorded testimony", kind: "claim", text: "Mara authorizes the flush. She says the tower promised an evacuation. The signature proves authorization; her explanation still needs corroboration." },
  { id: "order", flag: "memory_order", time: "02:16", title: "The counter-order", source: "Helion command receipt", kind: "fact", text: "The exported receipt records an instruction canceling evacuation while retaining the flush. Its contents are visible; the issuing key still needs independent verification during The Week." },
  { id: "roster", flag: "memory_roster", time: "02:19", title: "The living witness", source: "Shift roster and exit log", kind: "fact", text: "Ivo Pell and Junie Calder were on shift. Nia Pell signed the housing slip and reached a service exit. She can corroborate the receipt, but a public roster would expose where she sleeps." },
] as const;
export function memoryDisposition(state: GameState): string {
  if (state.flags.memory_intact) return "Complete archive";
  if (state.flags.memory_redacted) return "Protected roster";
  if (state.flags.memory_witness) return "Witness chain";
  if (state.flags.memory_prepared) return state.flags.memory_public_claim ? "Public allegation · issuer unverified" : "Bounded account · issuer unverified";
  if (state.flags.memory_reconstructed) return "Sequence compared · custody undecided";
  if (FRAGMENTS.every((fragment) => state.flags[fragment.flag])) return "Sources inspected · account undecided";
  return "Unexamined hour";
}
export function aftermath(state: GameState): { title: string; text: string }[] {
  const account = state.journal.some((entry) => entry.id === "nia-account");
  const heard = state.flags.heard_memo || state.journal.some((entry) => entry.id === "ward-nine");
  const rows = [
    { title: "Ward Nine", text: state.flags.spoke_names ? "Sera places your testimony beside the names. Neighbors have a public account to challenge the maintenance report." : state.flags.confirmed_leak ? "Sera records where the leak began. The wards can trace a source beyond the tower's account." : state.flags.ives_took_list ? "Helion controls the paper list. Sera begins another from the people still willing to visit." : state.flags.testimony_published ? "Sera retains your public account and its source limits. You left the memorial without speaking the names; the inquiry still has a record." : "Sera keeps restoring the names without your testimony. The maintenance report remains unchallenged by you." },
    { title: "Mara", text: state.flags.order_verified ? "Her signature and Helion's counter-order survive together. An investigator can distinguish her decision from the tower's later instruction." : state.flags.memory_intact ? "Her signature and the exported counter-order survive together. The issuing key remains unverified; preserving a receipt did not independently authenticate it." : state.flags.memory_redacted ? "Her signature survives with the worker locations withheld. The public account protects people and leaves a gap an investigator must explain." : heard ? "Her reason survives in your account. The tower's command chain still needs independent corroboration." : "You brought no recorded account of her decision to the wall. The tower's explanation remains unchallenged by you." },
  ];
  if (state.flags.memory_assurance_heard || state.flags.memory_channel_heard) rows.push({ title: "Mara’s answers", text: `${state.flags.memory_assurance_heard ? "Mara said she accepted a crew assignment without waiting for an exit count. Her account is retained as testimony, not a dispatch confirmation. " : ""}${state.flags.memory_channel_heard ? "She named a shift relay, not an independently identified dispatcher. " : ""}Questioning her did not erase her authorization or authenticate the cancellation.` });
  if (state.flags.witness_safe) rows.push({ title: "Nia Pell", text: account ? "Nia reaches a room outside Helion's tenancy register. She leaves a recorded account with Sera and chooses when it becomes public." : "Nia reaches a room outside Helion's tenancy register. Her account has not been attached to the evidence." });
  else if (state.flags.witness_lost) rows.push({ title: "Nia Pell", text: state.flags.witness_relocated ? `Nia reaches a second, private room. Her first location remains in the tower's records; moving again did not erase that breach.${account ? " Her approved account remains with Sera." : " Her account has not been attached to the evidence."}` : account ? "Nia receives clinic care. Lumen keeps her account, but Nia's location is now in the tower's records." : "Nia receives clinic care, but her location is now in the tower's records. Her account has not been attached to the evidence." });
  else if (state.flags.memory_witness || state.flags.memory_redacted) rows.push({ title: "Nia Pell", text: "You kept her location out of the archive. Her route remains unresolved; protecting an identity did not move the person." });
  if (state.flags.betrayed_lumen) rows.push({ title: "Lumen", text: "She stops using your marker as a promise. The clinic remains open; the next person must ask without your name." });
  if (state.flags.origin_helped) rows.push({ title: "Your old streets", text: "Your origin contact remembers that you returned the favor. A route, receipt, or shelter survives beyond this job." });
  if (state.flags.memory_source_shared) rows.push({ title: "The public packet", text: "Neighbors can inspect an independent source beside the original account, with worker locations withheld. The two decisions remain distinct." });
  else if (state.flags.memory_corrected) rows.push({ title: "The public packet", text: state.flags.order_verified ? "Your earlier correction remains attached to the allegation. Independent corroboration was obtained later; the original uncertainty and correction have not been erased." : "Your correction remains attached to the allegation. The receipt's issuer is still unverified; the earlier sentence has not been erased." });
  else if (state.flags.memory_doubled_down) rows.push({ title: "The public packet", text: "You repeated the allegation without an independent source. A neighbor withdrew his name from its distribution; the source challenge remains unanswered." });
  else if (state.flags.memory_public_claim) rows.push({ title: "The public packet", text: state.flags.order_verified ? "The original allegation has since gained independent corroboration. You did not return to attach that source to the neighborhood packet." : "The packet names Helion before its issuing key is authenticated. The allegation remains a claim, not independent proof." });
  if (state.flags.visited_nia) rows.push({ title: "The visit", text: account ? "You returned through the clinic and heard Nia's limits directly. Her approved words remain hers to authorize." : "You returned through the clinic. Nia had not authorized an account; the recorder stayed off." });
  if (state.flags.archive_custody) rows.push({ title: "Edda", text: state.flags.edda_exposed || state.flags.archive_method_face || state.flags.archive_method_nerve ? `The source can be traced to Edda. Her archive shift was suspended pending review.${state.flags.edda_supported ? " Your forty-creds contribution bridges the shift; it does not settle the review or erase exposure." : " The employment review remains unresolved."}` : "The circulating source withholds Edda’s name. Her shifts remain posted; Sera retains the original for inspection." });
  if (state.flags.edda_shift_done) rows.push({ title: "Edda’s payroll request", text: state.flags.edda_shift_declined ? "She declined a payroll application. Her suspended shift and records inquiry remain unresolved." : `${shiftResponse(state)} Private employment consent changed no public source permission.` });
  if (state.flags.testimony_published) rows.push({ title: "The public hearing", text: `${state.flags.testimony_source ? state.flags.archive_key_authenticated ? "The filed account identifies an authenticated issuing key." : "The filed account distinguishes independent corroboration from digital-key authentication." : "The filed account leaves corroboration unresolved. Public confidence supplied no new evidence."} ${state.flags.nia_public_consent ? "Nia authorized her approved words for this account through Sera, with her address withheld." : "Nia’s private recording was not quoted publicly."}${state.flags.testimony_corrected ? " The unsupported claim and its correction remain attached." : ""}` });
  else if (state.flags.testimony_withdrawn) rows.push({ title: "The public hearing", text: "You withdrew the draft. Attendees may remember the hearing; Nia’s recording was not opened to public circulation." });
  if (state.flags.nia_contact_set) rows.push({ title: "Nia’s contact boundary", text: state.flags.nia_contact_relay ? "Questions can be left through the clinic relay. Nia decides whether to answer; no address or new public permission was supplied." : "You agreed to pause further questions. Her already recorded account keeps its existing limits." });
  if (state.flags.notice_done) rows.push({ title: "Clinic distribution", text: state.flags.notice_unresolved ? "The bundle was left with staff. Receipt and attendance remain unknown." : state.flags.notice_monitored ? `The public window was observed and callers requested another time.${state.flags.notice_private_reply_booked ? " A private reply channel was funded; new appointments remain unconfirmed." : state.flags.notice_window_withdrawn ? " The window was withdrawn; no replacement was confirmed." : " No replacement channel was arranged."} The earlier observation remains; no home list was published.` : state.flags.notice_receipt_observed ? "Lumen showed two private receipt acknowledgements. Other receipts and attendance remain unknown." : "Distribution was arranged without a public home list. No patient receipt or attendance was observed by you." });
  for (const kit of equippedKits(state)) rows.push({ title: "Field equipment", text: `The ${kit.name} remains in your kit. It was available for specific mission checks without replacing a safe room, source, or person’s consent.` });
  if (state.flags.week_recovered) rows.push({ title: "Your recovery", text: state.flags.recovery_clinic ? "You paid for staffed recovery. The pressure eased; the money stayed spent, and your outside promises kept their own status." : state.flags.recovery_favor ? "The clinic covered your rest at a cost to its trust. Recovery did not erase a location breach or verify a source." : "You took a short rest beside the canal. It eased pressure without completing the work waiting outside." });
  if (state.flags.pump_done) rows.push({ title: "The clinic coolant", text: state.flags.pump_restored ? `The spare circuit restored cooling.${state.flags.pump_inspection_booked ? " A follow-up inspection is booked; it has not happened yet." : " Another inspection remains due."}${state.flags.pump_rebate ? " Helion retains your contractor handle and station number from the forty-creds rebate, without patient names." : " The neighborhood keeps its own repair record."} The repair authenticates no historical order.` : state.flags.pump_supplies_saved ? "The medicines reached another cold cabinet. The failed pump still needs a replacement relay." : "You left the transfer to clinic staff. Their delivery outcome was not observed by you." });
  if (state.flags.freight_started || state.flags.freight_declined) rows.push({ title: "Asa’s freight delivery", text: freightOutcome(state) });
  if (state.flags.shelter_started || state.flags.shelter_declined) rows.push({ title: "Shelter neighbors", text: shelterOutcome(state) + (state.flags.shelter_followup_paid ? " You funded their laundry afterward." : state.flags.shelter_followup_helped ? " You helped carry their laundry afterward." : "") });
  return rows;
}
