import { spendWindow, WINDOW_OPEN_FLAGS, windowRemaining, windowResume } from "../chapel-window";
import { kitBonuses } from "../loadout";
import type { Scene } from "../types";

export const WINDOW_SCENES: Record<string, Scene> = {
  chapel_window_plan: {
    id: "chapel_window_plan", location: "Glass Chapel service bench", speaker: "Quill",
    text: s => `Service window: ${windowRemaining(s)} of 3 action opportunities remain. The patrol is checking the far landing. It will return after three pieces of work, not after three real-world minutes. Reading, settings and saving spend nothing.\n\nScouting opens a timed Ghost crossing. Inspecting opens a Chrome disconnect if successful. Each preparation spends one opportunity; committing entry spends another, and a quiet exit needs one left. A direct Nerve hatch attempt saves preparation but risks strain. Looking up both routes can leave no quiet exit. You can pause without resetting the count.`,
    choices: [
      { id: "window-scout-gap", label: "Scout the patrol gap. Spend 1 opportunity.", requireAnyFlag: WINDOW_OPEN_FLAGS, hideIfAnyFlag: ["chapel_window_scouted", "chapel_window_0"], effects: s => ({ ...spendWindow(s), flags: [...spendWindow(s).flags!, "chapel_window_scouted"] }), next: windowResume },
      { id: "window-inspect-reader", label: "Inspect the reader. Chrome 8; spend 1 opportunity.", requireAnyFlag: WINDOW_OPEN_FLAGS, hideIfAnyFlag: ["chapel_window_inspected", "chapel_window_0"], check: { stat: "chrome", dc: 8, label: "Inspect within the service window", itemBonuses: kitBonuses("chrome") }, effects: s => ({ ...spendWindow(s), flags: [...spendWindow(s).flags!, "chapel_window_inspected"] }), successEffects: { flags: ["chapel_window_reader"] }, failEffects: { flags: ["chapel_window_query_seen"], strain: 1 }, resultSuccess: "The disconnect is accessible. Its entry still costs an opportunity and one strain; save an opportunity for the exit.", resultFail: "The reader logs the inspection and refuses the disconnect. The spent opportunity stays spent; the hatch and patrol route remain.", nextSuccess: windowResume, nextFail: windowResume },
      { id: "window-use-gap", label: "Commit the scouted crossing. Ghost 8; spend 1 opportunity.", detail: "Scouting adds +2. Failure returns you to ordinary doors with patrol attention and strain; there is no second window attempt.", requireFlag: "chapel_window_scouted", requireAnyFlag: WINDOW_OPEN_FLAGS, hideIfFlag: "chapel_window_0", check: { stat: "ghost", dc: 8, label: "Cross the service interval", flagBonuses: [{ flag: "chapel_window_scouted", amount: 2, label: "Scouted patrol" }, { flag: "chapel_window_query_seen", amount: -1, label: "Query noticed" }], itemBonuses: [...kitBonuses("ghost"), { item: "layout-scrap", amount: 1 }] }, effects: spendWindow, successEffects: { flags: ["chapel_window_entered", "chapel_window_ghost", "quiet"] }, failEffects: { flags: ["chapel_window_failed", "watched"], strain: 1 }, resultSuccess: "You reach the service landing between passes. Choose the exit before the patrol returns.", resultFail: "The patrol turns early. You stay outside and draw its attention. Ordinary doors are still available.", nextSuccess: "chapel_window_exit", nextFail: "chapel_window_expired" },
      { id: "window-use-reader", label: "Use the inspected disconnect. Spend 1 opportunity; add 1 strain.", requireFlag: "chapel_window_reader", requireAnyFlag: WINDOW_OPEN_FLAGS, hideIfFlag: "chapel_window_0", effects: s => ({ ...spendWindow(s), strain: 1, flags: [...spendWindow(s).flags!, "chapel_window_entered", "chapel_method_chrome", "quiet"] }), next: "chapel_window_exit" },
      { id: "window-force-hatch", label: "Hold the service hatch. Nerve 8; spend 1 opportunity.", detail: "No preparation required. Add 1 strain on success or failure. Failure draws attention; the ordinary doors remain.", requireAnyFlag: WINDOW_OPEN_FLAGS, hideIfFlag: "chapel_window_0", check: { stat: "nerve", dc: 8, label: "Hold the service hatch", itemBonuses: kitBonuses("nerve") }, effects: s => ({ ...spendWindow(s), strain: 1 }), successEffects: { flags: ["chapel_window_entered", "chapel_window_nerve", "quiet"] }, failEffects: { flags: ["chapel_window_failed", "watched"] }, resultSuccess: "You hold the hatch until its spring clears. The strained latch stays visible. Choose your exit.", resultFail: "The hatch snaps shut. The patrol notices your struggle, but you can return to the ordinary doors.", nextSuccess: "chapel_window_exit", nextFail: "chapel_window_expired" },
      { id: "pause-chapel-window", label: "Pause and keep the remaining allowance saved.", next: "route" },
    ],
  },
  chapel_window_exit: {
    id: "chapel_window_exit", location: "Glass Chapel service landing",
    text: s => `Service window: ${windowRemaining(s)} action opportunities remain. ${windowRemaining(s) ? "The return patrol has not reached this landing. One opportunity buys the quiet maintenance exit." : "The patrol is back. The quiet maintenance exit is closed."}\n\nThe staffed stair remains passable without money or a roll. It adds one strain and a visitor watch. Getting inside and choosing a quiet exit are separate decisions.`,
    choices: [
      { id: "window-quiet-exit", label: "Take the quiet maintenance exit. Spend 1 opportunity.", requireFlag: "chapel_window_entered", requireAnyFlag: WINDOW_OPEN_FLAGS, hideIfFlag: "chapel_window_0", effects: s => ({ ...spendWindow(s), flags: [...spendWindow(s).flags!, "chapel_window_done", "chapel_window_quiet_exit"] }), next: "undercroft" },
      { id: "window-staffed-exit", label: "Use the staffed stair. No fee; add 1 strain and a visitor watch.", requireFlag: "chapel_window_entered", effects: s => ({ strain: 1, flags: ["chapel_window_done", "chapel_window_staffed_exit", "watched", ...(windowRemaining(s) === 0 ? ["chapel_window_expired"] : [])] }), next: "undercroft" },
    ],
  },
  chapel_window_expired: {
    id: "chapel_window_expired", location: "Glass Chapel service bench", speaker: "Quill",
    text: s => `${s.flags.chapel_window_failed ? "The attempted crossing failed. The patrol has your outline; another die cannot reopen this window." : "The service window closed before entry. The patrol noticed the extra work at the bench."}\n\nReturn to the ordinary doors without a fee. Patrol attention stays recorded. The free hatch remains available; this missed window cannot stop the campaign or grant access by itself.`,
    choices: [{ id: "window-return-doors", label: "Return to the ordinary doors. No fee; patrol attention remains.", effects: { flags: ["chapel_window_done", "chapel_window_expired", "watched"] }, next: "route" }],
  },
};
