import type { Choice, GameState, Scene } from "../types";
export const responseChoice: Choice = { id: "hear-mara-response", label: "Hear Mara’s present-day request at the clinic.", detail: "A voluntary reply, separate from her recorded hour. Negotiate its recipient and clinic involvement.", requireFlag: "heard_memo", hideIfAnyFlag: ["response_done", "response_declined", "act2_done"], next: s => s.flags.response_private_consent ? "act2_response_dispatch" : s.flags.response_started ? "act2_response_agenda" : "act2_response_invitation" };
export const maraResponseVisit: Choice = { id: "visit-mara-response", label: "Return to Mara about her reply.", requireFlag: "response_started", hideIfFlag: "response_visit", next: "act3_response_visit" };
export const lumenBoundaryVisit: Choice = { id: "visit-lumen-boundary", label: "Hear Lumen’s own answer about future contact.", requireFlag: "response_started", hideIfFlag: "lumen_boundary_visit", next: "act3_lumen_boundary" };
const room = "Clinic side room, Ward Four";
export const CHARACTER_ARC_SCENES: Record<string, Scene> = {
 act2_response_invitation: {id:"act2_response_invitation",location:room,speaker:"Mara",text:"Mara sits beside the window with an envelope she has not sealed. This is her voice now, not a fragment replaying in the glass.\n\n'I want to answer in my own name. A private statement to the Ward Nine records desk. I won't make the clinic my alibi.'\n\nLumen brings a second chair. 'And I won't sign as your sponsor. We can still sit at the same table.'",choices:[
  {id:"listen-response-terms",label:"Sit down. Hear what each of them will agree to.",effects:{flags:["response_started","met_lumen"]},next:"act2_response_agenda"},
  {id:"decline-response-request",label:"Decline to carry a statement.",effects:{flags:["response_started","response_declined"]},next:"act2_middle"}
 ]},
 act2_response_agenda: {id:"act2_response_agenda",location:room,speaker:"Mara",text:"The envelope has room for a name and a recipient. Neither woman reaches for your pen.\n\nMara wants to enter her own response at the records desk. Lumen offers a room for this conversation, not the clinic's endorsement. Choose the proposal you want them to answer.",choices:[
  {id:"propose-private-response",label:"Mara’s own name. The private records desk. No clinic endorsement.",effects:{flags:["response_private_consent"],journal:[{id:"mara-response-terms",kind:"fact",text:"Mara authorized her own current statement for the private Ward Nine records desk only. Lumen did not endorse it. No public release, witness permission or historical authentication was supplied."}]},next:"act2_response_terms"},
  {id:"propose-public-response",label:"Ask Mara to put the statement on the public board instead.",effects:{flags:["response_public_refused"],journal:[{id:"response-public-refusal",kind:"fact",text:"Mara refused public release of her present-day statement this week. Private records submission remains possible; her refusal is not erased by a revised proposal."}]},next:"act2_response_refusal"},
  {id:"propose-clinic-endorsement",label:"Ask Lumen to attach the clinic’s name as sponsor.",effects:{flags:["response_clinic_refused"],journal:[{id:"response-clinic-refusal",kind:"fact",text:"Lumen refused clinic endorsement of Mara's statement. Hosting a conversation is not sponsorship; her refusal remains recorded after revision."}]},next:"act2_response_refusal"},
  {id:"leave-response-agenda",label:"Leave the proposal unanswered.",effects:{flags:["response_done","response_pending"]},next:"act2_middle"}
 ]},
 act2_response_refusal: {id:"act2_response_refusal",location:room,speaker:"Mara",text:s=>`${s.flags.response_public_refused ? "Mara turns the envelope over. 'Not the board. Not this week. I will answer the desk in my own name. I won't give you a crowd because you asked for one.'" : "Lumen moves the clinic pad out of reach. 'A chair and a lamp are what I offered. You don't get to turn them into a signature.' Mara waits for you to answer her, too."}\n\nThe private proposal is still available. You can accept those limits or leave the request pending.`,choices:[
  {id:"revise-private-response",label:"Revise to Mara’s named private reply, without a clinic sponsor.",effects:{flags:["response_private_consent","response_revised"],journal:[{id:"mara-response-terms",kind:"fact",text:"After a refused proposal, Mara authorized only her named private statement to the records desk. The original refusal remains; Lumen supplied no clinic endorsement."}]},next:"act2_response_terms"},
  {id:"withdraw-response-proposal",label:"Withdraw. Leave the statement with Mara.",effects:{flags:["response_done","response_pending"]},next:"act2_middle"}
 ]},
 act2_response_terms: {id:"act2_response_terms",location:room,speaker:"Mara",text:"Mara writes her name herself. The sheet describes her decision and asks to be entered as a respondent. No worker list is enclosed.\n\n'An answer is not an acquittal,' she says. Lumen leaves the clinic pad in its drawer.\n\nBefore you arrange dispatch, there is time for one small question. You can also let the silence stand.",choices:[
  {id:"ask-mara-tomorrow",label:"Ask Mara what she wants tomorrow to look like.",hideIfFlag:"response_question_done",next:"act2_mara_quiet"},
  {id:"ask-lumen-staying",label:"Ask Lumen why she keeps coming back to this clinic.",hideIfFlag:"response_question_done",next:"act2_lumen_quiet"},
  {id:"arrange-response-dispatch",label:"Let the quiet stand. Arrange the sealed reply.",next:"act2_response_dispatch"}
 ]},
 act2_mara_quiet:{id:"act2_mara_quiet",location:room,speaker:"Mara",text:"Mara looks at the cup rather than the envelope.\n\n'I want a morning that doesn't begin with someone else choosing what I remember. That won't give the night shift their morning back.'\n\nFor a moment she is neither a voice in your pocket nor the name at the bottom of a memo. Then she turns the statement toward herself and checks what she has written.",choices:[{id:"keep-mara-quiet-answer",label:"Keep her hope beside the responsibility she still bears.",effects:{flags:["response_question_done","mara_quiet_heard"],journal:[{id:"mara-tomorrow",kind:"claim",text:"Mara says she wants a morning in which she chooses what she remembers. This is her present hope, not an observed treatment outcome or an acquittal."}]},next:"act2_response_dispatch"}]},
 act2_lumen_quiet:{id:"act2_lumen_quiet",location:room,speaker:"Sister Lumen",text:"Lumen turns the spare chair toward the window.\n\n'Because somebody should know which cup they take their tea in. Even when the city has made a case file out of them.'\n\nShe lifts Mara's cup to wipe the ring beneath it, then puts it back in the same place. Her care does not need a signature on Mara's statement.",choices:[{id:"keep-lumen-quiet-answer",label:"Let care and endorsement remain separate.",effects:{flags:["response_question_done","lumen_quiet_heard"],journal:[{id:"lumen-staying",kind:"claim",text:"Lumen says ordinary attention is why she returns to the clinic. Her care and hosting do not endorse Mara's statement or authorize quotation."}]},next:"act2_response_dispatch"}]},
 act2_response_dispatch:{id:"act2_response_dispatch",location:room,speaker:"Mara",text:"The sealed envelope contains Mara's current statement, addressed privately to the Ward Nine records desk. She has kept her own name on it.\n\nWalk it to the intake slot, or pay a courier fifteen creds. Either records dispatch; the desk's answer comes later. You can leave it sealed here and return before the week ends.",choices:[
  {id:"walk-private-response",label:"Walk the sealed reply to the private intake slot.",detail:"One strain. Dispatch is not an inquiry decision.",requireFlag:"response_private_consent",hideIfFlag:"response_sent",effects:{strain:1,flags:["response_sent","response_walked"]},next:"act2_response_receipt"},
  {id:"courier-private-response",label:"Pay fifteen creds for private courier dispatch.",detail:"The courier carries only Mara’s named statement, without a worker list or clinic endorsement.",requireFlag:"response_private_consent",hideIfFlag:"response_sent",requireCreds:15,effects:{creds:-15,flags:["response_sent","response_courier"]},next:"act2_response_receipt"},
  {id:"defer-private-response",label:"Leave the envelope sealed here. Keep dispatch open.",next:"act2_middle"}
 ]},
 act2_response_receipt:{id:"act2_response_receipt",location:room,speaker:"Mara",text:s=>`${s.flags.response_walked ? "You return with the intake slot's dispatch stub." : "The courier leaves a dispatch stub on the table."} Mara folds it beside her copy.\n\n'Now I wait for an answer I can't write for them.'\n\nThe statement has been sent privately. The records desk has not yet replied, and its inquiry remains open.`,choices:[{id:"record-response-dispatch",label:"Keep the dispatch stub. Leave the desk’s answer open.",effects:{flags:["response_done"],journal:[{id:"mara-response-dispatch",kind:"fact",text:"Mara's separately authorized, named private statement was dispatched to the Ward Nine records desk. It contained no worker list or clinic endorsement. Receipt and any inquiry decision remain unobserved."}]},next:"act2_middle"}]},
 act3_response_visit:{id:"act3_response_visit",location:room,speaker:"Mara",text:s=>s.flags.response_sent ? "Mara has the records desk's returned intake slip under her cup. Her named response has been received into the unanswered queue. There is no finding attached.\n\n'They can ask me now,' she says. 'That was what I wanted my name there for.'" : s.flags.response_declined ? "Mara still has the envelope. You declined before undertaking dispatch.\n\n'You didn't promise me a receipt,' she says. 'I'll find another way to send it.'" : "Mara still has the envelope. The proposal or dispatch was left open when the week ended.\n\n'It hasn't reached the desk,' she says. 'Don't put an answer where the waiting is.'",choices:[
  {id:"read-response-intake",label:"Read the intake slip. Record receipt, with no inquiry decision.",requireFlag:"response_sent",effects:{flags:["response_received"],journal:[{id:"mara-response-intake",kind:"fact",text:"The Ward Nine records desk acknowledged receiving Mara's named private response into an unanswered queue. No inquiry finding, historical authentication, acquittal or public release followed."}]},next:"act3_mara_followup"},
  {id:"keep-response-unfinished",label:"Keep the reply unfinished in the record.",hideIfFlag:"response_sent",next:"act3_mara_followup"}
 ]},
 act3_mara_followup:{id:"act3_mara_followup",location:room,speaker:"Mara",text:s=>`${s.flags.response_public_refused ? s.flags.response_sent ? "Mara keeps her refusal of the public board beside the new proposal. 'Private meant private. I'm glad that sentence survived the journey.'" : "Mara keeps her refusal beside the unfinished proposal. 'No board, and no dispatch yet. Leave both lines there.'" : "Mara puts her name where you can both see it. 'I signed the old order. This page doesn't take my hand off it.'"}\n\n${s.flags.mara_quiet_heard ? "She asks whether you remember the morning she described. There is no treatment report to answer her with, only the hope she trusted you to hear." : "She asks you to carry no comforting story about her that she hasn't told you."}\n\n${s.flags.response_received ? "The reply is in the desk's queue. The inquiry is still waiting." : "The envelope remains with her. Nothing has reached the desk through you."}`,choices:[{id:"finish-mara-response",label:"Leave her answer and its limits in her own name.",effects:{flags:["response_visit"]},next:"act3_arrival"}]},
 act3_lumen_boundary:{id:"act3_lumen_boundary",location:room,speaker:"Sister Lumen",text:s=>`${s.flags.response_clinic_refused ? "Lumen points to the pad she refused to sign. 'The clinic stayed out of the endorsement. Keep the refusal with the rest.'" : "Lumen sets two clean cups on the shelf. 'We gave the conversation a room. We didn't give it our name.'"}\n\n${s.flags.betrayed_lumen ? "'You sold the week after walking with me. Helping with this reply doesn't make that disappear. Leave future messages at the desk; don't speak as my partner.'" : s.flags.pact_fake && (s.flags.act1_sold || s.flags.act1_both) ? "'You promised to break the hour and sold it instead. This envelope is a different act. Future messages stay at the desk; don't call me your partner.'" : "'You may leave a private message at the desk. I decide whether to answer. That's all the permission I'm giving.'"}\n\nShe turns back to the kettle. Ordinary work has waited long enough.`,choices:[{id:"respect-lumen-boundary",label:"Keep the contact limit without adding her name to the statement.",effects:s=>({flags:["lumen_boundary_visit",s.flags.betrayed_lumen || s.flags.pact_fake && (s.flags.act1_sold || s.flags.act1_both)?"lumen_contact_limited":"lumen_private_contact"],journal:[{id:"lumen-contact-limit",kind:"fact",text:"Lumen permits leaving a private message at the desk, with no promise to answer or authorize public quotation, partnership or clinic endorsement. Earlier betrayal remains recorded."}]}),next:"act3_arrival"}]}
};
